### SIGNUP ROUTE
POST http://localhost:3000/api/signup 
Content-Type: application/json

{
  "email": "user9@user.com",
  "password": "user9",
  "re_password": "user9"
}

### LOGIN ROUTE
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "user5@user.com",
  "password": "user5"
}

### UPDATE USER PROFILE
PATCH http://localhost:3000/api/users/64762560db8b65634143cfb1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODU0NzMxNDQsImV4cCI6MTY4NTQ3Njc0NCwiYXVkIjoiNjQ3NjI1NjBkYjhiNjU2MzQxNDNjZmIxIiwiaXNzIjoiYmFja2VuZHJlc3RhcGlzcGxvb3QuY29tIn0.tAisXNOj_izpO_kP18QpLha1YC3-ICMSaqhg-i0GEt0
Content-Type: application/json

{
  "name": "User Five", 
  "age": 5
}

### CREATE AN ARTICLE
POST http://localhost:3000/api/users/64762560db8b65634143cfb1/articles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODU0NzA1NzMsImV4cCI6MTY4NTQ3NDE3MywiYXVkIjoiNjQ3NjI1NjBkYjhiNjU2MzQxNDNjZmIxIiwiaXNzIjoiYmFja2VuZHJlc3RhcGlzcGxvb3QuY29tIn0.usFAV9VhhAWP1L82g7uShuS7P8-1XKsVkjS6Kjnp-38
Content-Type: application/json

{
  "art": "User 5's third article post."
}

### GET ALL ARTICLES
GET http://localhost:3000/api/articles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODU0NzA1NzMsImV4cCI6MTY4NTQ3NDE3MywiYXVkIjoiNjQ3NjI1NjBkYjhiNjU2MzQxNDNjZmIxIiwiaXNzIjoiYmFja2VuZHJlc3RhcGlzcGxvb3QuY29tIn0.usFAV9VhhAWP1L82g7uShuS7P8-1XKsVkjS6Kjnp-38


